### ISSUE TITLE
代码演示 1) 原型链法 

### ISSUE THREAD

**Issue by OSMeteor** [jimuyouyou/node-interview-questions#1]
Animal.prototype.sayName = {
        alert(this.name);
    };

  Animal.prototype.sayName = function(){
        alert(this.name);
    };

**Comment by NexZhu** [comment]
Person.prototype = Animal.prototype; // 人继承自动物

Person.prototype = new Animal(); // 人继承自动物

**Comment by jimuyouyou** [comment]
OSMeteor mentioned issue has been fixed in https://github.com/jimuyouyou/node-interview-questions/commit/0cd597e10edb95f4cafebbdf176634f859b86183

NexZhu: New Animal()是实例化了。一般来说继承是类级别的，不需要实例化。

**Comment by NexZhu** [comment]
@jimuyouyou 原来这样写不是继承

这样Person.prototype与Animal.prototype是同一个对象，修改Person.prototype会影响父类Animal的prototype，而不是重载。
