### ISSUE TITLE
一点点疑问

### ISSUE THREAD

**Issue by LastKing** [jimuyouyou/node-interview-questions#10]
1. exports is not actually a global but rather local to each module.
原文[global.exports](https://nodejs.org/dist/latest-v7.x/docs/api/globals.html#globals_exports)

exports 并不是一个真正意义上的全局方法吧

**Comment by jimuyouyou** [comment]
已修复。非常感谢参与！

代码变化：https://github.com/jimuyouyou/node-interview-questions/commit/a71e77fada9fe6edc35c8556c890733aded0d143
