### ISSUE TITLE
还有一个比较常被问到的问题

### ISSUE THREAD

**Issue by WebPuY** [jimuyouyou/node-interview-questions#13]
如何捕获NodeJS中的错误，有几种方法

**Comment by jimuyouyou** [comment]
@WebPuY , 在 https://github.com/jimuyouyou/node-interview-questions/commit/f73c070a0c5c320b039152f83391157691ea561d

添加了该问题。如果您感觉还可以改进，麻烦继续提建议，或提交pull request。非常感谢！
