### ISSUE TITLE
setImmediate  和 nextTick 的优先级

### ISSUE THREAD

**Issue by GladiusK** [jimuyouyou/node-interview-questions#2]
node中的事件循环是什么样子的 
这个知识点里面 关于 setImmediate  和 nextTick  执行 优先级
我觉得应该是 nextTick  先执行 。

**Comment by jimuyouyou** [comment]
https://github.com/nodejs/node/blob/master/doc/topics/event-loop-timers-and-nexttick.md
你是正确的。内容已更改为nextTick >> setImmediate >> setTimeout/setInterval
但是正如官网所说执行顺序具有不确定性，再就是如何区分当前事件队列，当前注册，当前运行的timers是当前注册的，还是以前注册的，等各种细分会变得更加复杂。图片暂时保留不变，为的是有一个总体感觉。

**Comment by qufei1993** [comment]
可以看下这个 process.nextTick与setTimeout递归调用区别 

https://github.com/Q-Angelo/Summarize/blob/master/nodejs/operational_mechanism.md#processnexttick%E4%B8%8Esettimeout%E9%80%92%E5%BD%92%E8%B0%83%E7%94%A8%E5%8C%BA%E5%88%AB
