### ISSUE TITLE
关于捕获EventEmitter的错误事件

### ISSUE THREAD

**Issue by coolzc** [jimuyouyou/node-interview-questions#3]
摘自nodejs的文档:
https://nodejs.org/dist/latest-v4.x/docs/api/events.html#events_error_events

> To guard against crashing the Node.js process, developers can either register a listener for the process.on('uncaughtException') event or use the domain module (Note, however, that the domain module has been deprecated).
> const myEmitter = new MyEmitter();
> 
> process.on('uncaughtException', (err) => {
>   console.log('whoops! there was an error');
> });
> 
> myEmitter.emit('error', new Error('whoops!'));
>   // Prints: whoops! there was an error
> As a best practice, developers should always register listeners for the 'error' event:
> 
> const myEmitter = new MyEmitter();
> myEmitter.on('error', (err) => {
>   console.log('whoops! there was an error');
> });
> myEmitter.emit('error', new Error('whoops!'));
>   // Prints: whoops! there was an error

以下这一段是不是要改一下，鉴于domain has been deprecated，文档推荐的best的方法用EventEmitter的实例去监听错误。

> 1. 怎么捕获EventEmitter的错误事件?
>    参考答案: 监听error事件即可．如果有多个EventEmitter,也可以用domain来统一处理错误事件.
> 
> 代码演示
> 
> ```
> var domain = require('domain');
> var myDomain = domain.create();
> myDomain.on('error', function(err){
>     console.log('domain接收到的错误事件:', err);
> }); // 接收事件并打印
> myDomain.run(function(){
>     var emitter1 = new MyEmitter();
>     emitter1.emit('error', '错误事件来自emitter1');
>     emitter2 = new MyEmitter();
>     emitter2.emit('error', '错误事件来自emitter2');
> });
> ```

**Comment by jimuyouyou** [comment]
EventEmitter的实例去监听错误官网推荐的第一种方法，是基于一个前提，那就是必须主动emit('error')事件，然后才可以监听。事实上，真实项目中有太多的意外，比如三层以上回调中有个未定义变量，数据库连接失败，数组越界等这些情况，你无法在每一层去检查所有可能的错误并主动往最上一级发送错误事件。唯一的选择就是服务器自动挂掉了。

可是，很多时候，比如数组越界，可能是浏览器传入参数有问题，我们只想对当前用户停止服务，服务器不应该挂掉。这就是要求必须有个最外层调用者的try-catch,用以区分对待。目前来看，还没有什么原生支持，可以完全替代domains的作用。 

不过ES7的async, await可以一定程度上实现

**Comment by coolzc** [comment]
感谢回答
